name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Configure git to use the access token
      run: |
        git config --global url."https://${{ secrets.TOKENGITHUB }}@github.com/".insteadOf "https://github.com/"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Debug git configuration
      run: git config --global --list

    - name: Verify git access
      run: git ls-remote https://github.com/viantonugroho11/go-boilerplate.git

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

  generate-and-commit-changelog:
    runs-on: ubuntu-latest
    needs: setup-and-build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install git-chglog
      run: |
        go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Fetch tags
      run: git fetch --tags

    - name: Generate Changelog
      run: |
        git-chglog -o CHANGELOG.md
        TAG=$(git describe --tags --always)
        echo "Update changelog for $TAG"
        sed -i "1s/^/## $TAG\n\n/" CHANGELOG.md

    - name: Commit Changelog
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add CHANGELOG.md  # Staging file yang ingin di-commit
        git commit -m "Update CHANGELOG.md"
      env:
        GITHUB_TOKEN: ${{ secrets.TOKENGITHUB }}

    - name: Debug Changelog
      run: cat CHANGELOG.md

    # - name: Commit Changelog
    #   if: github.event_name == 'push'
    #   run: |
    #     git add .
    #     git commit -m "Update changelog for $(git describe --tags --abbrev=0 2>/dev/null || echo 'Initial commit')"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOKENGITHUB }}

    - name: Push Changelog
      if: github.event_name == 'push'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKENGITHUB }}
        branch: main
  tag-and-release:
    runs-on: ubuntu-latest
    needs: generate-and-commit-changelog

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Build Tag
      if: github.event_name == 'push'
      run: |
        git fetch --prune --unshallow
        LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "Last tag: $LAST_TAG"
        VERSION=${LAST_TAG//v/}
        echo "Current version: $VERSION"
        IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
        PATCH=${VERSION_PARTS[2]}
        PATCH=$((PATCH + 1))
        NEW_TAG="v${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH"
        echo "New tag: $NEW_TAG"
        git tag $NEW_TAG
        git push origin $NEW_TAG
      env:
        GITHUB_TOKEN: ${{ secrets.TOKENGITHUB }}
